# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQtDesigner_Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(800, 500)
        self.Create_Lobby = QtWidgets.QPushButton(Menu)
        self.Create_Lobby.setGeometry(QtCore.QRect(600, 390, 90, 28))
        self.Create_Lobby.setObjectName("Create_Lobby")
        self.Send_Message = QtWidgets.QPushButton(Menu)
        self.Send_Message.setGeometry(QtCore.QRect(650, 340, 90, 28))
        self.Send_Message.setObjectName("Send_Message")
        self.Join_Lobby = QtWidgets.QPushButton(Menu)
        self.Join_Lobby.setGeometry(QtCore.QRect(490, 350, 90, 28))
        self.Join_Lobby.setObjectName("Join_Lobby")
        self.Leave_Lobby = QtWidgets.QPushButton(Menu)
        self.Leave_Lobby.setGeometry(QtCore.QRect(490, 400, 90, 28))
        self.Leave_Lobby.setObjectName("Leave_Lobby")
        self.Message_Box = QtWidgets.QTextEdit(Menu)
        self.Message_Box.setGeometry(QtCore.QRect(500, 30, 251, 191))
        self.Message_Box.setReadOnly(True)
        self.Message_Box.setObjectName("Message_Box")
        self.Lobby_List = QtWidgets.QListView(Menu)
        self.Lobby_List.setGeometry(QtCore.QRect(40, 30, 311, 311))
        self.Lobby_List.setObjectName("Lobby_List")
        self.Start_Lobby = QtWidgets.QPushButton(Menu)
        self.Start_Lobby.setGeometry(QtCore.QRect(590, 440, 90, 28))
        self.Start_Lobby.setObjectName("Start_Lobby")
        self.Message_Input = QtWidgets.QLineEdit(Menu)
        self.Message_Input.setGeometry(QtCore.QRect(500, 220, 251, 28))
        self.Message_Input.setText("")
        self.Message_Input.setObjectName("Message_Input")

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Main Menu"))
        self.Create_Lobby.setText(_translate("Menu", "Create Lobby"))
        self.Send_Message.setText(_translate("Menu", "Send Message"))
        self.Join_Lobby.setText(_translate("Menu", "Join Lobby"))
        self.Leave_Lobby.setText(_translate("Menu", "Leave Lobby"))
        self.Start_Lobby.setText(_translate("Menu", "Start Lobby"))
        self.Message_Input.setPlaceholderText(_translate("Menu", "Enter message..."))
