# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQtDesigner_Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(800, 500)
        self.Create_Lobby = QtWidgets.QPushButton(Menu)
        self.Create_Lobby.setGeometry(QtCore.QRect(230, 340, 90, 28))
        self.Create_Lobby.setObjectName("Create_Lobby")
        self.Join_Lobby = QtWidgets.QPushButton(Menu)
        self.Join_Lobby.setGeometry(QtCore.QRect(30, 340, 90, 28))
        self.Join_Lobby.setObjectName("Join_Lobby")
        self.Leave_Lobby = QtWidgets.QPushButton(Menu)
        self.Leave_Lobby.setGeometry(QtCore.QRect(130, 340, 90, 28))
        self.Leave_Lobby.setObjectName("Leave_Lobby")
        self.Start_Lobby = QtWidgets.QPushButton(Menu)
        self.Start_Lobby.setGeometry(QtCore.QRect(330, 340, 90, 28))
        self.Start_Lobby.setObjectName("Start_Lobby")
        self.Message_Input = QtWidgets.QLineEdit(Menu)
        self.Message_Input.setGeometry(QtCore.QRect(530, 440, 251, 28))
        self.Message_Input.setText("")
        self.Message_Input.setObjectName("Message_Input")
        self.Lobby_Tree = QtWidgets.QTreeWidget(Menu)
        self.Lobby_Tree.setGeometry(QtCore.QRect(20, 10, 471, 311))
        self.Lobby_Tree.setObjectName("Lobby_Tree")
        self.Chat_Tab = QtWidgets.QTabWidget(Menu)
        self.Chat_Tab.setGeometry(QtCore.QRect(530, 10, 250, 431))
        self.Chat_Tab.setTabBarAutoHide(False)
        self.Chat_Tab.setObjectName("Chat_Tab")
        self.Global_Chat = QtWidgets.QWidget()
        self.Global_Chat.setObjectName("Global_Chat")
        self.Global_Chat_Box = QtWidgets.QTextEdit(self.Global_Chat)
        self.Global_Chat_Box.setGeometry(QtCore.QRect(-1, -1, 251, 402))
        self.Global_Chat_Box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Global_Chat_Box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Global_Chat_Box.setReadOnly(True)
        self.Global_Chat_Box.setObjectName("Global_Chat_Box")
        self.Chat_Tab.addTab(self.Global_Chat, "")
        self.Lobby_Chat = QtWidgets.QWidget()
        self.Lobby_Chat.setObjectName("Lobby_Chat")
        self.Lobby_Chat_Box = QtWidgets.QTextEdit(self.Lobby_Chat)
        self.Lobby_Chat_Box.setGeometry(QtCore.QRect(-1, -1, 251, 402))
        self.Lobby_Chat_Box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Lobby_Chat_Box.setReadOnly(True)
        self.Lobby_Chat_Box.setObjectName("Lobby_Chat_Box")
        self.Chat_Tab.addTab(self.Lobby_Chat, "")

        self.retranslateUi(Menu)
        self.Chat_Tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Main Menu"))
        self.Create_Lobby.setText(_translate("Menu", "Create Lobby"))
        self.Join_Lobby.setText(_translate("Menu", "Join Lobby"))
        self.Leave_Lobby.setText(_translate("Menu", "Leave Lobby"))
        self.Start_Lobby.setText(_translate("Menu", "Start Lobby"))
        self.Message_Input.setPlaceholderText(_translate("Menu", "Enter message..."))
        self.Lobby_Tree.headerItem().setText(0, _translate("Menu", "Lobby ID"))
        self.Lobby_Tree.headerItem().setText(1, _translate("Menu", "Players"))
        self.Lobby_Tree.headerItem().setText(2, _translate("Menu", "Type"))
        self.Lobby_Tree.headerItem().setText(3, _translate("Menu", "Live"))
        self.Chat_Tab.setTabText(self.Chat_Tab.indexOf(self.Global_Chat), _translate("Menu", "Global Chat"))
        self.Chat_Tab.setTabText(self.Chat_Tab.indexOf(self.Lobby_Chat), _translate("Menu", "Lobby Chat"))
